spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: gjw605134015
    url: jdbc:mysql://127.0.0.1/springcloud_sell?characterEncoding=utf-8&SSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env: dev
girl:
  name: 1267671212
  age: 1821212
