spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: gjw605134015
    url: jdbc:mysql://127.0.0.1/springcloud_sell?characterEncoding=utf-8&SSL=false
  jpa:
    show-sql: true
